### ISSUE TITLE
Add basic nodes to the editor

### ISSUE THREAD

**Issue by mouhamadalmounayar** [mouhamadalmounayar/ngx-traak#2]
## Summary
Implement basic nodes like `Paragraph`, `OrderedList`, `BulletList`, `TaskList`, `Heading`.

## Description
The nodes mentioned above should be provided to the user with the library, to be eventually passed with the `config` object.

## Acceptance Criteria

- **Given** an editor component instance **Then** the user should be able to use already defined nodes in the config passed as inputs

## Technical Details

- Use the `prosemirror-list` package for list related nodes.

## Tasks
- [x] Implement `Paragraph` node
- [x] Implement `OrderedList` node
- [x] Implement `BulletList` node
- [x] Implement `TaskList` node
- [x] Implement `Heading` node
- [x] Write tests for each node
- [x] Update documentation to include new nodes

## Related Issues

-  #1
